### ISSUE TITLE
Pas de bloquage lors de l'ajout d'une commande

### ISSUE THREAD

**Issue by ewanvidal** [polytech-dijon/kfet#30]
On peut appuyer plusieurs fois sur le bouton sauvegarder lorsqu'on créer une commande et donc faire la même commande plusieurs fois sans que le modal se ferme

**Comment by Starmania** [comment]
J'ai pensé a deux moyens de le résoudre, soit un lock côté UI (du type [submitLock, setSubmitLock] = useState(false); try{ if submitLock return; ...} finally { setSubmitLock(false) }, soit un nonce par commande qui permet de drop une requête... C'est quoi le mieux pour vous ?

**Comment by Starmania** [comment]
J'ai pensé a deux moyens de le résoudre, soit un lock côté UI (du type [submitLock, setSubmitLock] = useState(false); try{ if submitLock return; ...} finally { setSubmitLock(false) }, soit un nonce par commande qui permet de drop une requête... C'est quoi le mieux pour vous ?
